
services:
  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: ""
      POSTGRES_PASSWORD_FILE: ""
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty12

  tests:
    environment:
      SERVER_URL: http://localhost:$SERVER_PORT
